services:
  web:
    image: myapp
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - mydata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=authorization_server
    ports:
      - 5432

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/authorization_server -user=postgres -password=123 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  mydata: